name: BL-Phantom-Analysis-Fiji
channels:
  - conda-forge
  - defaults
dependencies:
  - Python >= 3.7
  - imglyb >= 2.0.1
  - jgo >= 1.0.3
  - JPype >= 1.3.0
  - labeling >= 0.1.12
  - matplotlib (optional, for ij.py.show function only)
  - NumPy
  - pip
    # - some-pip-package if you need any pip packages that are not available in Conda
  - scyjava >= 1.8.0
  - xarray
